version: '2.1'
services:

  sc-smtp:
    image: ctindel/sc-smtp:${SC_ENV}
    container_name: sc-smtp
    restart: always
    environment:
      AWS_REGION: "us-east-1"
      SMTP_USERNAME: ${SC_SMTP_USERNAME}
      SMTP_PASSWORD: ${SC_SMTP_PASSWORD}
    networks:
      sc-net:
        aliases:
          - smtp
    ports:
      - 25:25

  sc-mysql:
    image: ctindel/sc-mysql:${SC_ENV}
    container_name: sc-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "squirrelcart"
      MYSQL_USER: "squirrelcart"
      MYSQL_PASSWORD: "squirrelcart"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      sc-net:
        aliases:
          - db
          - mysql
    ports:
      - 3306:3306

  sc-app:
    depends_on:
      - sc-smtp
      - sc-mysql
    image: ctindel/sc-app:${SC_ENV}
    container_name: sc-app
    environment:
      - APACHE_SERVER_NAME=ctindel.prod.sa.elastic.co
    restart: always
    networks:
      sc-net:
        aliases:
          - squirrelcart
          - app
    ports:
      - 8080:8080

  adminer:
    image: adminer
    depends_on:
      - sc-mysql
    container_name: adminer
    restart: always
    networks:
      sc-net:
    ports:
      - 8080:8080
      - 8443:8443

networks:
  sc-net:
    driver: bridge
