version: '2.1'
services:

  sc-mysql-build:
    build:
      context: docker_mysql
    image: ctindel/sc-mysql-build:${SC_ENV}
    container_name: sc-mysql-build
    restart: always
    environment:
      MYSQL_DATABASE: "squirrelcart"
      MYSQL_USER: "squirrelcart"
      MYSQL_PASSWORD: "squirrelcart"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      sc-build-net:
        aliases:
          - db
          - mysql
    ports:
      - 3306:3306

  sc-app-build:
    depends_on:
      - sc-mysql-build
    build:
      context: docker_squirrelcart
    image: ctindel/sc-app-build:${SC_ENV}
    container_name: sc-app-build
    environment:
      - APACHE_SERVER_NAME=ctindel-build.prod.sa.elastic.co
    restart: always
    networks:
      sc-build-net:
        aliases:
          - squirrelcart
          - app
    ports:
      - 8080:8080

networks:
  sc-build-net:
    driver: bridge
