version: '2.1'
services:

  sc-smtp-build:
    build:
      context: docker_smtp
    image: ctindel/sc-smtp-build:${SC_ENV}
    container_name: sc-smtp-build
    restart: on-failure
    environment:
      AWS_REGION: "us-east-1"
      SMTP_USERNAME: ${SC_SMTP_USERNAME}
      SMTP_PASSWORD: ${SC_SMTP_PASSWORD}
    networks:
      sc-build-net:
        aliases:
          - smtp
    ports:
      - 25:25

  sc-mysql-build:
    build:
      context: docker_mysql
    image: ctindel/sc-mysql-build:${SC_ENV}
    container_name: sc-mysql-build
    restart: on-failure
    environment:
      MYSQL_DATABASE: "squirrelcart"
      MYSQL_USER: "squirrelcart"
      MYSQL_PASSWORD: "squirrelcart"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /tmp/sc/mysql_build_data:/var/lib/mysql
    networks:
      sc-build-net:
        aliases:
          - db
          - mysql
    ports:
      - 3306:3306

  sc-app-build:
    depends_on:
      - sc-smtp-build
      - sc-mysql-build
    build:
      context: docker_squirrelcart
    image: ctindel/sc-app-build:${SC_ENV}
    container_name: sc-app-build
    environment:
      - APACHE_SERVER_NAME=ctindel-build.prod.sa.elastic.co
    restart: on-failure
    networks:
      sc-build-net:
        aliases:
          - squirrelcart
          - app
    ports:
      - 8080:8080
      - 8443:8443

networks:
  sc-build-net:
    driver: bridge
