#cloud-config
debug: true
disable_root: false
hostname: ${hostname}
fqdn: ${hostname}.${sa_dns_domain}
manage_etc_hosts: true
packages:
growpart:
    mode: auto
    devices: ['/']
    ignore_growroot_disabled: false
bootcmd:
    - mkdir /home/centos/squirrel
    - chown centos:centos /home/centos/squirrel
write_files:
    - path: /etc/systemd/system/update_route53_mapping.service
      encoding: base64
      content: ${base64encode(update_route53_mapping_service)}
      owner: "root:root"
      permissions: "0644"
    - path: /home/centos/squirrel/setup_storage.sh
      encoding: base64
      content: ${base64encode(setup_storage_sh)}
      owner: "centos:centos"
      permissions: "0755"
    - path: /home/centos/squirrel/start_squirrel.sh
      encoding: base64
      content: ${base64encode(start_squirrel_sh)}
      owner: "centos:centos"
      permissions: "0755"
    - path: /home/centos/squirrel/docker-compose.yml
      encoding: base64
      content: ${base64encode(squirrel_docker_compose)}
      owner: "centos:centos"
      permissions: "0644"
runcmd:
    # We want to clear out peoples' demo ML jobs every week
    # just let the ASG reboot this box every day
    #- echo "/sbin/halt" | /usr/bin/at midnight $$(date -d 'next Saturday' '+%Y-%m-%d')
    - systemctl enable --now update_route53_mapping
    - bash /home/centos/squirrel/start_squirrel.sh
